#!/usr/bin/env python3
"""Analytics Reporter — weekly Instagram metrics report via email or JSON."""

import os, sys, json, smtplib
from datetime import datetime, timezone
from pathlib import Path
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv
import requests

load_dotenv()

GRAPH_BASE = "https://graph.facebook.com/v21.0"
TOKEN = os.environ["GRAPH_PAGE_TOKEN"]
IG_USER_ID = os.environ["GRAPH_IG_USER_ID"]
ACCOUNT_NAME = os.environ.get("ACCOUNT_NAME", "instagram")
SMTP_USER = os.environ.get("SMTP_USER", "")
SMTP_PASS = os.environ.get("SMTP_PASS", "")
REPORT_EMAIL = "noreply@ooumph.com"

HISTORY_FILE = Path("analytics_history.json")
REPORT_FILE = Path("analytics_report.json")


def load_history():
    if HISTORY_FILE.exists():
        try:
            return json.loads(HISTORY_FILE.read_text())
        except Exception:
            return []
    return []


def save_history(data):
    HISTORY_FILE.write_text(json.dumps(data, indent=2))


def get_profile():
    url = f"{GRAPH_BASE}/{IG_USER_ID}"
    params = {"fields": "followers_count,media_count,profile_views", "access_token": TOKEN}
    r = requests.get(url, params=params, timeout=30)
    if r.status_code == 200:
        return r.json()
    print(f"⚠️  Profile fetch failed: {r.json().get('error', {}).get('message', r.text)}")
    return {}


def get_recent_media():
    url = f"{GRAPH_BASE}/{IG_USER_ID}/media"
    params = {
        "fields": "id,like_count,comments_count,timestamp,caption",
        "limit": 10,
        "access_token": TOKEN,
    }
    r = requests.get(url, params=params, timeout=30)
    if r.status_code == 200:
        return r.json().get("data", [])
    print(f"⚠️  Media fetch failed: {r.json().get('error', {}).get('message', r.text)}")
    return []


def build_report(profile: dict, media: list) -> dict:
    total_likes = sum(m.get("like_count", 0) for m in media)
    total_comments = sum(m.get("comments_count", 0) for m in media)
    avg_engagement = round((total_likes + total_comments) / max(len(media), 1), 2)

    top_post = max(media, key=lambda m: m.get("like_count", 0) + m.get("comments_count", 0) * 2, default={})

    return {
        "account": ACCOUNT_NAME,
        "date": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        "followers_count": profile.get("followers_count", "N/A"),
        "media_count": profile.get("media_count", "N/A"),
        "profile_views": profile.get("profile_views", "N/A"),
        "last_10_posts": {
            "total_likes": total_likes,
            "total_comments": total_comments,
            "avg_engagement": avg_engagement,
            "post_count": len(media),
        },
        "top_post": {
            "id": top_post.get("id", "N/A"),
            "likes": top_post.get("like_count", 0),
            "comments": top_post.get("comments_count", 0),
            "caption_preview": (top_post.get("caption", "") or "")[:100],
            "timestamp": top_post.get("timestamp", "N/A"),
        },
    }


def format_email_body(report: dict) -> str:
    lp = report["last_10_posts"]
    tp = report["top_post"]
    return f"""
Weekly Instagram Analytics Report
Account: @{report['account']}
Date: {report['date']}

PROFILE OVERVIEW
----------------
Followers:     {report['followers_count']}
Total Posts:   {report['media_count']}
Profile Views: {report['profile_views']}

LAST 10 POSTS PERFORMANCE
--------------------------
Total Likes:       {lp['total_likes']}
Total Comments:    {lp['total_comments']}
Avg Engagement:    {lp['avg_engagement']} per post
Posts Analyzed:    {lp['post_count']}

TOP PERFORMING POST
--------------------
Post ID:    {tp['id']}
Likes:      {tp['likes']}
Comments:   {tp['comments']}
Posted:     {tp['timestamp']}
Caption:    {tp['caption_preview']}...

---
Generated by Ooumph IG Automation
"""


def send_email(subject: str, body: str) -> bool:
    try:
        msg = MIMEMultipart()
        msg["From"] = SMTP_USER
        msg["To"] = REPORT_EMAIL
        msg["Subject"] = subject
        msg.attach(MIMEText(body, "plain"))

        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(SMTP_USER, SMTP_PASS)
            server.sendmail(SMTP_USER, REPORT_EMAIL, msg.as_string())
        return True
    except Exception as e:
        print(f"  ✗ Email send failed: {e}")
        return False


def main():
    print(f"[Analytics Reporter] Account: {ACCOUNT_NAME} | IG user: {IG_USER_ID}")

    profile = get_profile()
    media = get_recent_media()

    if not profile and not media:
        print("✗ Could not fetch any data. Exiting.")
        sys.exit(1)

    report = build_report(profile, media)
    print(f"  Followers: {report['followers_count']} | Avg engagement: {report['last_10_posts']['avg_engagement']}")

    # Save to history
    history = load_history()
    history.append(report)
    save_history(history)
    print(f"  ✓ Saved to {HISTORY_FILE}")

    # Save current report
    REPORT_FILE.write_text(json.dumps(report, indent=2))
    print(f"  ✓ Saved to {REPORT_FILE}")

    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    subject = f"[{ACCOUNT_NAME}] Weekly Analytics — {date_str}"
    body = format_email_body(report)

    if SMTP_USER and SMTP_PASS:
        print(f"  Sending email to {REPORT_EMAIL}...")
        if send_email(subject, body):
            print(f"  ✓ Email sent successfully")
        else:
            print(f"  ⚠️  Email failed — report saved to JSON instead")
    else:
        print("  ⚠️  SMTP_USER/SMTP_PASS not set — printing report to console:")
        print(body)

    print(f"[Analytics Reporter] Done.")


if __name__ == "__main__":
    main()
